config/routes.rb
TicTacToe::Application.routes.draw do

  root 'static_pages#home'

  resources :sessions, only: [:new, :create, :destroy]
  resources :players, only: [:new, :create]

  delete '/signout', to: 'sessions#destroy'
  get '/move', to: 'games#move'
  get '/outcome', to: 'games#ouctome'

end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :game_players
  has_many :players, :through => :game_players

  validate :has_exactly_two_players

  private

    def has_exactly_two_players
      unless self.players.count == 2
        errors.add(:game, "Must have only 2 players")
      end
    end

end

app/models/game_player.rb
class GamePlayer < ActiveRecord::Base
  belongs_to :game 
  belongs_to :player
end

app/models/player.rb
class Player < ActiveRecord::Base
  
  before_save { email.downcase! }

  has_many :game_players
  has_many :games, :through => :game_players

  validates :name, :email, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper
  include ComputerHelper
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def move
    board = format_board(params[:board])
    move = computer_move(board)
    data = [move, "O"]
    render json: data
  end

  def outcome
    board = format_board(params[:board])
    binding.pry
    data = []
    render json: data
  end

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def new
  end

  def create
    @player = Player.new(player_params)
    if @player.save
      sign_in @player
      redirect_to root_url
    else
      render 'new'
    end
  end

  private

    def player_params
      params.require(:player).permit(:name, :email)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = Player.find_by_email(params[:session][:email].downcase)
    if user
      sign_in user
      redirect_to root_url
    else
      flash.now[:error] = "Invalid email"
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    @player = Player.new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/computer_helper.rb
module ComputerHelper
  POSITIONS = [['top-left','top-mid','top-right'],
               ['mid-left','mid-mid','mid-right'],
               ['bottom-left','bottom-mid','bottom-right']]

  def computer_move(board)
    move = ""

    while move == ""
      rand_row = rand(3)
      rand_col = rand(3)

      if board[rand_row][rand_col] == ""
        move = POSITIONS[rand_row][rand_col]
      end
    end
    move
  end

  def format_board(board_hash)
    board = []
    board_hash.each do |key, array|
      board << array
    end
    board
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    session[:user_id] = user.id
  end

  def current_user
    Player.find(session[:user_id]) if signed_in?
  end

  def signed_in?
    session[:user_id]
  end

  def sign_out
    session[:user_id] = nil
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TicTacToe</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shared/_gameboard.html.erb
<table id='board' class='container'>
  <tr>
    <td id='top-left' class='square'><p></p></td>
    <td id='top-mid' class='square'><p></p></td>
    <td id='top-right' class='square'><p></p></td>
  </tr>
  <tr>
    <td id='mid-left' class='square'><p></p></td>
    <td id='mid-mid' class='square'><p></p></td>
    <td id='mid-right' class='square'><p></p></td>
  </tr>
  <tr>
    <td id='bottom-left' class='square'><p></p></td>
    <td id='bottom-mid' class='square'><p></p></td>
    <td id='bottom-right' class='square'><p></p></td>
  </tr>
</table>

app/views/static_pages/_signin.html.erb
<h2>Sign in</h2>

<div>
	<%= form_for(:session, url: sessions_path) do |f| %>

		<%= f.label :email %>
		<%= f.text_field :email %>

		<%= f.submit "Sign in" %>
	<% end %>

	<h3>New user?</h3>
</div>

app/views/static_pages/_signup.html.erb
<h3>Sign up!</h3>
<div>
	<%= form_for @player do |f| %>
		<%= f.label :name %>
		<%= f.text_field :name %>

		<%= f.label :email %>
		<%= f.text_field :email %>

		<%= f.submit "Create my account" %>
	<% end %>
</div>

app/views/static_pages/home.html.erb
<h1>Play Tic Tac Toe!</h1>
<%= render 'shared/gameboard' %>